### ISSUE TITLE
suggest to cut a new release of Avian Diet Database

### ISSUE THREAD

**Issue by jhpoelen** [hurlbertlab/dietdatabase#165]
Hi @ahhurlbert et al.,

GloBI has been indexing your Avian Diet Database for quite a while now (almost 10 years!).

And, GloBI looks at "stable" releases for indexing. Can you please create a new release so that GloBI can incorporate the updated citation and more? 

Thanks!

-jorrit

**Comment by ahhurlbert** [comment]
Hi Jorrit,

We haven't added much in the last few years, but there were 2 new studies since the last release so I just created a new release.

Yes, it's been a long time! There's still plenty of data out there to ingest for us, so eventually I hope to ramp data entry effort back up again.

Best,
Allen

From: Jorrit Poelen ***@***.***>
Sent: Tuesday, June 25, 2024 8:53 AM
To: hurlbertlab/dietdatabase ***@***.***>
Cc: Hurlbert, Allen Hartley ***@***.***>; Mention ***@***.***>
Subject: [hurlbertlab/dietdatabase] suggest to cut a new release of Avian Diet Database (Issue #165)


Hi @ahhurlbert<https://github.com/ahhurlbert> et al.,

GloBI has been indexing your Avian Diet Database for quite a while now (almost 10 years!).

And, GloBI looks at "stable" releases for indexing. Can you please create a new release so that GloBI can incorporate the updated citation and more?

Thanks!

-jorrit

**Comment by jhpoelen** [comment]
@ahhurlbert great to hear that project is still actively maintained and thanks for cutting a release.

**Comment by ahhurlbert** [comment]
I created a new release in the github repo: https://github.com/hurlbertlab/dietdatabase/releases/tag/v.1.0.8

I assumed this would automatically show up in Zenodo. Remind me if there's another step I'm forgetting.

**Comment by jhpoelen** [comment]
Huh, weird. Look like the GitHub -> Zenodo integration stopped working for you somehow. Can you check whether your integration is still active somehow?

**Comment by ahhurlbert** [comment]
Someone from Zenodo helped and the new release should be showing now.

**Comment by jhpoelen** [comment]
Thanks for making this work! I can see your 1.0.8 release on Zenodo now.

![image](https://github.com/hurlbertlab/dietdatabase/assets/1084872/e2f074d6-3da4-449c-8b95-6a0a2f03d415)
