### ISSUE TITLE
Questions about problem scientific names

### ISSUE THREAD

**Issue by pwinner1** [hurlbertlab/dietdatabase#80]
For some of the scientific names, they include subspecies. Should this be included? In one instance, _Microbregma emarginatum granicolle_ was entered and valid in ITIS, but it still was on the problem names list.

_Ischaemum rugosum; Oryza latifolia; Rottboellia cochinchinensis_. How should this problem name be fixed? 

For many names, I can't seem to find a replacement. Either the genus exists and the species doesn't seem to exist (_Crepidodera helxines)_, or the scientific name as a whole doesn't provide any useful clues in a google search (_Tachys tripunctata_).

In the case that I come across multiple sources using a speicific scientific name, but it not being in ITIS, how should I decide that that name should be the replacement? How can I know that the name comes from a credible source?

I may be able to better explain these issues in person...

**Comment by ahhurlbert** [comment]
1) Drop the subspecies name, although you can mention it in the Notes field

2) I had a look at the original source, Basili & Temple 1999, and since the data really is for a group of grasses, I would simply drop the Scientific_Name entry and leave it at Family = Poaceae

3) _Crepidodera helxines_ is an example where, as you note, the genus is a good genus but the species name is not recognized by ITIS although it is recognized by other authorities (i.e., it's not a typo, just a name that not everyone is familiar with). I double-checked the original source, and did some Google searching around to convince myself of this (e.g. http://insectoid.info/insecta/coleoptera/chrysomelidae/crepidodera_helxines/). Given that, I would leave the name, leave the 'replacewith' field blank. Because this record will not match ITIS and therefore the higher taxonomic levels will not get filled automatically, you will want to make sure the Notes field actually specifies "Genus = Crepidodera & Family = Chrysomelidae & ..." for all of the taxonomic columns present in the Diet Database (i.e., including Order, Suborder, Class, Phylum, Kingdom).

4) _Tachys tripunctata_, I found one source related to the genus (https://zookeys.pensoft.net/articles.php?id=10033), but would probably treat this the same as the example above.

5) Your last question is best addressed with specific examples.

**Comment by pwinner1** [comment]
@ahhurlbert 

For _Cnemidotus   12-punctatus_, the genus seems to be Peltodytes, but 12-punctatus is still not a species that I can find any sources on. How would I make it drop the scientific name and have only the new genus? Putting "Genus = Peltodytes & ...." wouldn't change the scientific name already in the database, would it?

Similarly, _Hister?_ is only a genus, but it was entered under scientific name. How do I correct this?

**Comment by ahhurlbert** [comment]
1. For Cnemidotus, leaving the 'replacewith' field blank will replace the currently unaccepted name with nothing. Not clear to me whether genus should be Peltodytes or Haliplus (Cnemidotus may have been split into those two, so it could be either), in which case in the Notes we might put "Genus = "" & Family = Haliplidae & Suborder = Adephaga & Order = Coleoptera & Class = Insecta & Phylum = Arthropoda & Kingdom = Animalia".

2. Same as above, leave 'replacewith' blank, and then "Genus = Hister & ..." in Notes.

**Comment by pwinner1** [comment]
@ahhurlbert 
When I find that a scientific name is recognized by sources other than ITIS, and for example, put "Genus = Crepidodera & Family = Chrysomelidae & ..." in the notes to fill higher taxonomic levels, is the scientific name supposed to be dropped when the fix_prob_names() is used (this is with leaving the 'replacewith' field blank)? I've found that for these names, the genus is now the lowest level filled, not scientific name even though I thought we wanted to keep them.

**Comment by ahhurlbert** [comment]
I believed we resolved this, but @pwinner1 please re-open if there are further issues.
